// Code generated by protoc-gen-go. DO NOT EDIT.
// source: securepacket.proto

/*
Package securepacket is a generated protocol buffer package.

It is generated from these files:
	securepacket.proto

It has these top-level messages:
	Packet
*/
package securepacket

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Packet struct {
	SrcIP    string `protobuf:"bytes,1,opt,name=srcIP" json:"srcIP,omitempty"`
	SrcPort  string `protobuf:"bytes,2,opt,name=srcPort" json:"srcPort,omitempty"`
	DestIP   string `protobuf:"bytes,3,opt,name=destIP" json:"destIP,omitempty"`
	DestPort string `protobuf:"bytes,4,opt,name=destPort" json:"destPort,omitempty"`
	Packtype string `protobuf:"bytes,5,opt,name=packtype" json:"packtype,omitempty"`
	Payload  []byte `protobuf:"bytes,6,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (m *Packet) Reset()                    { *m = Packet{} }
func (m *Packet) String() string            { return proto.CompactTextString(m) }
func (*Packet) ProtoMessage()               {}
func (*Packet) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Packet) GetSrcIP() string {
	if m != nil {
		return m.SrcIP
	}
	return ""
}

func (m *Packet) GetSrcPort() string {
	if m != nil {
		return m.SrcPort
	}
	return ""
}

func (m *Packet) GetDestIP() string {
	if m != nil {
		return m.DestIP
	}
	return ""
}

func (m *Packet) GetDestPort() string {
	if m != nil {
		return m.DestPort
	}
	return ""
}

func (m *Packet) GetPacktype() string {
	if m != nil {
		return m.Packtype
	}
	return ""
}

func (m *Packet) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func init() {
	proto.RegisterType((*Packet)(nil), "securepacket.Packet")
}

func init() { proto.RegisterFile("securepacket.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 155 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2a, 0x4e, 0x4d, 0x2e,
	0x2d, 0x4a, 0x2d, 0x48, 0x4c, 0xce, 0x4e, 0x2d, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2,
	0x41, 0x16, 0x53, 0x5a, 0xc4, 0xc8, 0xc5, 0x16, 0x00, 0x66, 0x0a, 0x89, 0x70, 0xb1, 0x16, 0x17,
	0x25, 0x7b, 0x06, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x41, 0x38, 0x42, 0x12, 0x5c, 0xec,
	0xc5, 0x45, 0xc9, 0x01, 0xf9, 0x45, 0x25, 0x12, 0x4c, 0x60, 0x71, 0x18, 0x57, 0x48, 0x8c, 0x8b,
	0x2d, 0x25, 0xb5, 0xb8, 0xc4, 0x33, 0x40, 0x82, 0x19, 0x2c, 0x01, 0xe5, 0x09, 0x49, 0x71, 0x71,
	0x80, 0x58, 0x60, 0x2d, 0x2c, 0x60, 0x19, 0x38, 0x1f, 0x24, 0x07, 0xb2, 0xb8, 0xa4, 0xb2, 0x20,
	0x55, 0x82, 0x15, 0x22, 0x07, 0xe3, 0x83, 0x6c, 0x2a, 0x48, 0xac, 0xcc, 0xc9, 0x4f, 0x4c, 0x91,
	0x60, 0x53, 0x60, 0xd4, 0xe0, 0x09, 0x82, 0x71, 0x93, 0xd8, 0xc0, 0x2e, 0x37, 0x06, 0x04, 0x00,
	0x00, 0xff, 0xff, 0x10, 0xe4, 0xe0, 0x82, 0xcf, 0x00, 0x00, 0x00,
}
